### ISSUE TITLE
Needs list of supported devices

### ISSUE THREAD

**Issue by hl01** [victorzappi/LDSP#4]
Let's make a list of supported devices! :)

**Comment by victorzappi** [comment]
Yes, good point! We will start working on this very soon. We have some fixes to take care of beforehand.
For the time being, the 'phones' dir shows all the devices and configurations that we successfully tested [including some notes], organized by brand.

**Comment by carlasophiet** [comment]
This is done today 23.10.2023- will keep it updated!
Added a list of phones that for now won't work as well with LDSP due to lack of mixer_paths.xml file.

**Comment by victorzappi** [comment]
List added to readme on 2023/10/23 and will be kept up-to-date.
